Fix audio distortion
ploopyco/headphones pull request #8
Opened 2023-04-03 22:05 UTC by george-norton

Fixed a `fix16_t `overflow which can lead to audio distortion due to the PCM samples sign flipping.
Removed the previous workaround which reduced the input sample bitdepth to 14bits.
Added simple tool which enables running the audio filtering stages on a PC.

_**Note:** the default audio volume may need tweaking - it will be louder now._

2023-04-04 20:30 UTC, ploopyco requested changes

2023-04-04 20:36 UTC, george-norton commented on firmware/code/run.c
Yes, I saw that but this line was not changed in commit #1771cca when the input sample divisor was changed. So I wasn't sure if this should be removed altogether, or replaced by a divide by 2..

2023-04-04 20:39 UTC, george-norton commented on firmware/code/run.c
Removing it makes sense, but I can't check how the volume sounds.

2023-04-05 20:23 UTC, ploopyco approved these changes

2023-04-05 20:23 UTC, merged